name: eShopOnWeb Build and Test

# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        # Use a stable .NET 8 SDK, not a preview version
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./eShopOnWeb.sln

    - name: Build
      run: dotnet build ./eShopOnWeb.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ./eShopOnWeb.sln --configuration Release --no-build --verbosity normal
